// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace LogicApps.TestFramework.IntegrationTests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Nested-Foreach-and-Until-Loops-Sample-StepDefinition")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class Nested_Foreach_And_Until_Loops_Sample_StepDefinitionFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "", "Nested-Foreach-and-Until-Loops-Sample-StepDefinition", "\tAs a integration specialist\r\n\tI want to verify that to test the step definition " +
                "functionality in the test framework", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Foreach-Until-SampleStepDefinition.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Foreach-Until-SampleStepDefinition.feature.ndjson", 3);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validate complete workflow with nested structures")]
        public async global::System.Threading.Tasks.Task ValidateCompleteWorkflowWithNestedStructures()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validate complete workflow with nested structures", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.WhenAsync("Workflow \"prc-nestedloops-and-do-until\" is triggered", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table1.AddRow(new string[] {
                            "Recurrence",
                            "Succeeded"});
                table1.AddRow(new string[] {
                            "Initialize variables",
                            "Succeeded"});
                table1.AddRow(new string[] {
                            "Set variable",
                            "Succeeded"});
#line 11
    await testRunner.ThenAsync("The workflow executed these actions:", ((string)(null)), table1, "Then ");
#line hidden
#line 18
    await testRunner.AndAsync("The \"Set variable\" action has status \"Succeeded\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table2.AddRow(new string[] {
                            "For each number",
                            "Succeeded"});
                table2.AddRow(new string[] {
                            "Until",
                            "Succeeded"});
#line 21
    await testRunner.AndAsync("In \"Try\":", ((string)(null)), table2, "And ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table3.AddRow(new string[] {
                            "For each letter",
                            "Succeeded"});
                table3.AddRow(new string[] {
                            "Variable testString2 value less than 3",
                            "Succeeded"});
#line 27
    await testRunner.AndAsync("In \"Try.For each number[1]\":", ((string)(null)), table3, "And ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table4.AddRow(new string[] {
                            "For each letter",
                            "Succeeded"});
                table4.AddRow(new string[] {
                            "Variable testString2 value less than 3",
                            "Succeeded"});
#line 33
    await testRunner.AndAsync("All iterations of \"For each number\" executed:", ((string)(null)), table4, "And ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table5.AddRow(new string[] {
                            "Set variable testString",
                            "Succeeded"});
#line 39
    await testRunner.AndAsync("In \"Try.For each number[1].For each letter[2].For each character[3]\":", ((string)(null)), table5, "And ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table6.AddRow(new string[] {
                            "Set variable testString",
                            "Succeeded"});
#line 44
    await testRunner.AndAsync("All iterations of \"For each character\" executed:", ((string)(null)), table6, "And ");
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table7.AddRow(new string[] {
                            "Until2",
                            "Succeeded"});
                table7.AddRow(new string[] {
                            "Reset variable counter2",
                            "Succeeded"});
                table7.AddRow(new string[] {
                            "Set variable teststring until",
                            "Succeeded"});
                table7.AddRow(new string[] {
                            "Increment variable counter",
                            "Succeeded"});
                table7.AddRow(new string[] {
                            "Condition",
                            "Succeeded"});
#line 49
    await testRunner.AndAsync("In \"Try.Until[1]\":", ((string)(null)), table7, "And ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table8.AddRow(new string[] {
                            "Set variable untilCompleted",
                            "Skipped"});
#line 56
    await testRunner.AndAsync("In \"Try.Until[1].Condition\":", ((string)(null)), table8, "And ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table9.AddRow(new string[] {
                            "Increment variable counter3",
                            "Succeeded"});
#line 61
    await testRunner.AndAsync("In \"Try.Until[1].Until2[2].Until3[2]\":", ((string)(null)), table9, "And ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table10.AddRow(new string[] {
                            "Until2",
                            "Succeeded"});
                table10.AddRow(new string[] {
                            "Reset variable counter2",
                            "Succeeded"});
                table10.AddRow(new string[] {
                            "Set variable teststring until",
                            "Succeeded"});
                table10.AddRow(new string[] {
                            "Increment variable counter",
                            "Succeeded"});
                table10.AddRow(new string[] {
                            "Condition",
                            "Succeeded"});
#line 66
    await testRunner.AndAsync("All iterations of \"Until\" executed:", ((string)(null)), table10, "And ");
#line hidden
                global::Reqnroll.Table table11 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table11.AddRow(new string[] {
                            "Increment variable counter3",
                            "Succeeded"});
#line 75
    await testRunner.AndAsync("All iterations of \"Until3\" executed:", ((string)(null)), table11, "And ");
#line hidden
                global::Reqnroll.Table table12 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table12.AddRow(new string[] {
                            "Condition in try",
                            "Succeeded"});
#line 80
    await testRunner.AndAsync("In \"Try\":", ((string)(null)), table12, "And ");
#line hidden
                global::Reqnroll.Table table13 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table13.AddRow(new string[] {
                            "Set variable testString in condition",
                            "Succeeded"});
#line 85
    await testRunner.AndAsync("In the \"actions\" branch of \"Condition in try\":", ((string)(null)), table13, "And ");
#line hidden
                global::Reqnroll.Table table14 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table14.AddRow(new string[] {
                            "Set variable testString in condition",
                            "Succeeded"});
#line 90
    await testRunner.AndAsync("In \"Try.Condition in try.actions\":", ((string)(null)), table14, "And ");
#line hidden
                global::Reqnroll.Table table15 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table15.AddRow(new string[] {
                            "Set variable testString2 true",
                            "Succeeded"});
#line 95
    await testRunner.AndAsync("In \"Try.For each number[1].Variable testString2 value less than 3.actions\":", ((string)(null)), table15, "And ");
#line hidden
                global::Reqnroll.Table table16 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table16.AddRow(new string[] {
                            "Switch",
                            "Succeeded"});
#line 101
    await testRunner.AndAsync("In \"Try\":", ((string)(null)), table16, "And ");
#line hidden
                global::Reqnroll.Table table17 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table17.AddRow(new string[] {
                            "Set variable in switch",
                            "Succeeded"});
#line 106
    await testRunner.AndAsync("In the \"Default\" branch of \"Switch\":", ((string)(null)), table17, "And ");
#line hidden
                global::Reqnroll.Table table18 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table18.AddRow(new string[] {
                            "Set variable in switch",
                            "Succeeded"});
#line 111
    await testRunner.AndAsync("In \"Try.Switch.Default\":", ((string)(null)), table18, "And ");
#line hidden
                global::Reqnroll.Table table19 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table19.AddRow(new string[] {
                            "Set variable testString2 true",
                            "Succeeded"});
#line 116
    await testRunner.AndAsync("In \"Try.For each number[1].Variable testString2 value less than 3.actions\":", ((string)(null)), table19, "And ");
#line hidden
                global::Reqnroll.Table table20 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table20.AddRow(new string[] {
                            "Set variable testString2 false",
                            "Skipped"});
#line 119
    await testRunner.AndAsync("In \"Try.For each number[1].Variable testString2 value less than 3.else\":", ((string)(null)), table20, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
