// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace LogicApps.TestFramework.IntegrationTests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Receive-Process-Send-Sample-StepDefinition")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class Receive_Process_Send_Sample_StepDefinitionFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "", "Receive-Process-Send-Sample-StepDefinition", "\tAs a integration specialist\r\n\tI want to verify that chained correlated workflows" +
                " with nested structures are properly validated in the test framework", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Rcv-Prc-Snd-SampleStepDefinition.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Rcv-Prc-Snd-SampleStepDefinition.feature.ndjson", 4);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validate http request with file content")]
        public async global::System.Threading.Tasks.Task ValidateHttpRequestWithFileContent()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validate http request with file content", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.WhenAsync("Workflow \"rcvHttp\" is triggered with file \"sample-http-request-content.json\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table21 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table21.AddRow(new string[] {
                            "Initialize variables",
                            "Succeeded"});
#line 8
    await testRunner.ThenAsync("The workflow executed these actions:", ((string)(null)), table21, "Then ");
#line hidden
                global::Reqnroll.Table table22 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table22.AddRow(new string[] {
                            "Validate json schema",
                            "Succeeded"});
#line 11
    await testRunner.AndAsync("In \"Try\":", ((string)(null)), table22, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validate complete workflow chain")]
        public async global::System.Threading.Tasks.Task ValidateCompleteWorkflowChain()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validate complete workflow chain", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
    await testRunner.WhenAsync("Workflow \"rcv\" is triggered", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table23 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table23.AddRow(new string[] {
                            "Initialize variable sampleMessage",
                            "Succeeded"});
                table23.AddRow(new string[] {
                            "Initialize variable correlationId",
                            "Succeeded"});
                table23.AddRow(new string[] {
                            "Initialize variable counter",
                            "Succeeded"});
                table23.AddRow(new string[] {
                            "Initialize variable errorMessage",
                            "Succeeded"});
                table23.AddRow(new string[] {
                            "Initialize variable",
                            "Succeeded"});
#line 19
    await testRunner.ThenAsync("The workflow executed these actions:", ((string)(null)), table23, "Then ");
#line hidden
                global::Reqnroll.Table table24 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table24.AddRow(new string[] {
                            "Validate json schema",
                            "Succeeded"});
#line 26
    await testRunner.AndAsync("In \"Try\":", ((string)(null)), table24, "And ");
#line hidden
                global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table25.AddRow(new string[] {
                            "Increment variable counter",
                            "Succeeded"});
                table25.AddRow(new string[] {
                            "Write message payload to storage",
                            "Succeeded"});
                table25.AddRow(new string[] {
                            "Send claim-check message to topic",
                            "Succeeded"});
#line 29
    await testRunner.AndAsync("All iterations of \"For each item in items\" executed:", ((string)(null)), table25, "And ");
#line hidden
                global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table26.AddRow(new string[] {
                            "Send success tracked properties to table storage",
                            "Succeeded"});
                table26.AddRow(new string[] {
                            "Send success tracked properties to log analytics",
                            "Succeeded"});
#line 34
    await testRunner.AndAsync("In \"Try\":", ((string)(null)), table26, "And ");
#line hidden
                global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table27.AddRow(new string[] {
                            "Receive new claim-check message from queue",
                            "Succeeded"});
                table27.AddRow(new string[] {
                            "Initialize variable correlationId",
                            "Succeeded"});
                table27.AddRow(new string[] {
                            "Initialize variable errorMessage",
                            "Succeeded"});
#line 39
    await testRunner.ThenAsync("For all instances of \"prc\" with the same correlation:", ((string)(null)), table27, "Then ");
#line hidden
                global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table28.AddRow(new string[] {
                            "Retrieve message payload from storage",
                            "Succeeded"});
                table28.AddRow(new string[] {
                            "Transform source data type to target data type",
                            "Succeeded"});
                table28.AddRow(new string[] {
                            "Write message payload to storage",
                            "Succeeded"});
                table28.AddRow(new string[] {
                            "Send claim-check message to queue",
                            "Succeeded"});
                table28.AddRow(new string[] {
                            "Complete claim-check message in queue",
                            "Succeeded"});
                table28.AddRow(new string[] {
                            "Send success tracked properties to log analytics",
                            "Succeeded"});
#line 44
    await testRunner.AndAsync("In \"Try\":", ((string)(null)), table28, "And ");
#line hidden
                global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table29.AddRow(new string[] {
                            "Receive new claim-check message from queue",
                            "Succeeded"});
                table29.AddRow(new string[] {
                            "Initialize variable correlationId",
                            "Succeeded"});
                table29.AddRow(new string[] {
                            "Initialize variable errorMessage",
                            "Succeeded"});
#line 53
    await testRunner.ThenAsync("For all instances of \"snd\" with the same correlation:", ((string)(null)), table29, "Then ");
#line hidden
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table30.AddRow(new string[] {
                            "Retrieve message payload from storage",
                            "Succeeded"});
                table30.AddRow(new string[] {
                            "Post to google.com api",
                            "Failed"});
#line 58
    await testRunner.AndAsync("In \"Try\":", ((string)(null)), table30, "And ");
#line hidden
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table31.AddRow(new string[] {
                            "Set variable errorMessage to http response body",
                            "Succeeded"});
                table31.AddRow(new string[] {
                            "Throw exception",
                            "Succeeded"});
#line 62
    await testRunner.AndAsync("In \"Try.Check http status code.Default\":", ((string)(null)), table31, "And ");
#line hidden
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "StepName",
                            "Status"});
                table32.AddRow(new string[] {
                            "Complete claim-check message in queue",
                            "Succeeded"});
                table32.AddRow(new string[] {
                            "Send success tracked properties to log analytics",
                            "Succeeded"});
#line 66
    await testRunner.AndAsync("In \"Try\":", ((string)(null)), table32, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
