using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Public workflow model types intentionally expose concrete List<T> to allow direct Newtonsoft.Json deserialization into collections and to enable test/helpers to construct and mutate action lists without custom converters. Converting to interface types would require mapping or converters and risks breaking existing callers.", Scope = "namespaceanddescendants", Target = "~N:LogicApps.Management.Workflow")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "Action model types expose concrete List<T> by design to simplify construction, mutation and JSON deserialization in runtime and tests. Using readonly or interface types would complicate deserialization and test setup.", Scope = "namespaceanddescendants", Target = "~N:LogicApps.Management.Actions")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Collection properties are writable to support direct JSON deserialization and to allow test code and helpers to populate workflows and nested action trees without additional mapping.", Scope = "namespaceanddescendants", Target = "~N:LogicApps.Management.Workflow")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Action collections are intentionally mutable so callers and tests can build and modify nested action models; this aligns with the project's serialization approach and test patterns.", Scope = "namespaceanddescendants", Target = "~N:LogicApps.Management.Actions")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "`WorkflowDefinition.Actions` is a List<T> to allow direct manipulation and to simplify Newtonsoft.Json deserialization used across the codebase and tests.", Scope = "member", Target = "~P:LogicApps.Management.WorkflowDefinition.Actions")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Keeping `WorkflowDefinition.Actions` writable enables straightforward deserialization and test construction of workflow definitions; making it read-only would add mapping overhead.", Scope = "member", Target = "~P:LogicApps.Management.WorkflowDefinition.Actions")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "Primary constructors are a language feature but are not used here to keep constructors explicit across multiple overloads and to preserve existing initialization behaviour. Migrating would be a large refactor with little practical benefit.", Scope = "namespaceanddescendants", Target = "~N:LogicApps.Management.Factory")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "Action types perform explicit initialization in constructors for readability and to support complex setup; converting to primary constructors would reduce explicitness and require extensive refactoring.", Scope = "namespaceanddescendants", Target = "~N:LogicApps.Management.Actions")]
[assembly: SuppressMessage("Design", "CA1002:Do not expose generic lists", Justification = "<Pending>", Scope = "member", Target = "~M:LogicApps.Management.WorkflowRun.FindActionByName(System.String)~System.Collections.Generic.List{LogicApps.Management.Actions.BaseAction}")]
